addons:
  firefox: "54.0.1"

dist: trusty
language: ruby

cache:
  directories:
    - "travis_geckodriver"

rvm:
  - '2.4.1'

before_script:
  - if [ ! -d $PWD/travis_geckodriver ];  then mkdir $PWD/travis_geckodriver; fi
  - if [ ! -f $PWD/travis_geckodriver/geckodriver ]; then wget https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-linux64.tar.gz; fi
  - if [ ! -f $PWD/travis_geckodriver/geckodriver ]; then tar -xvf geckodriver-v0.16.0-linux64.tar.gz -C $PWD/travis_geckodriver; fi
  - "export PATH=$PWD/travis_geckodriver:$PATH"
  - "geckodriver --version"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

script: bundle exec rake ci
